#!/usr/bin/env python3
"""Generate docs/EMPIRICAL_TYPE_LABELS.md -- the final packer -> Type document --
from the empirical manifests produced by `packer-types finalize`.

Scans every manifest/empirical_types_*.yaml, collects each condition that carries an
EMPIRICAL (exact-consensus) Type label, and writes a single sorted markdown table.
Provisional/hypothesis-only rows are excluded: this document is the empirical result.
"""
from __future__ import annotations

import glob
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "docs" / "EMPIRICAL_TYPE_LABELS.md"


def main() -> int:
    rows: dict[str, dict] = {}
    manifests = sorted(glob.glob(str(REPO / "manifest" / "empirical_types_*.yaml")))
    for path in manifests:
        data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
        for cond in data.get("conditions", []):
            status = cond.get("label_status")
            label = cond.get("label")
            if status != "empirical_exact_trace_consensus" or not label:
                continue
            cid = cond.get("configuration_id")
            rows[cid] = {
                "family": cond.get("packer_family"),
                "version": cond.get("packer_version"),
                "test_case": cond.get("test_case_id"),
                "label": label,
                "runs": cond.get("completed_runs"),
                "evidence": cond.get("paper_evidence_level"),
            }

    ordered = sorted(rows.values(), key=lambda r: (str(r["family"]).lower(),
                                                   str(r["version"]), str(r["test_case"])))
    lines = [
        "# Empirical Packer-Type Labels",
        "",
        "Exact Ugarte et al. Type I–VI labels assigned **empirically** from real",
        "dynamic traces of packed corpus samples (see",
        "[AUTOMATIC_LABELING.md](AUTOMATIC_LABELING.md)). Each row is an",
        "**exact-consensus** label: the same Type observed across ≥2 distinct packed",
        "payloads × ≥3 repetitions each, under a certified backend. No approximations;",
        "no static hypotheses. This file is generated by",
        "`ops/qemu/build_label_document.py` and grows as more conditions are run.",
        "",
        f"**Conditions empirically labeled: {len(ordered)}**",
        "",
        "| Packer family | Version | Test case | Empirical Type | Runs | Evidence |",
        "|---|---|---|---|---|---|",
    ]
    for r in ordered:
        lines.append(
            f"| {r['family']} | {r['version']} | {r['test_case']} | "
            f"**{r['label']}** | {r['runs']} | {r['evidence'] or 'A_exact_layer_frame_trace'} |"
        )
    if not ordered:
        lines.append("| _(none yet — run a condition and finalize)_ | | | | | |")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(ordered)} empirical labels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
