#!/usr/bin/env python3
"""Generate docs/EMPIRICAL_TYPE_LABELS.md -- the final packer -> Type document --
from the empirical manifests produced by `packer-types finalize`.

Scans every manifest/empirical_types_*.yaml, collects each condition that carries an
EMPIRICAL (exact-consensus) Type label, and writes a single sorted markdown table.
Provisional/hypothesis-only rows are excluded: this document is the empirical result.
"""
from __future__ import annotations

import glob
import json
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "docs" / "EMPIRICAL_TYPE_LABELS.md"


RULE_BY_STATUS = {
    "empirical_exact_trace_consensus": "exact",
    "empirical_max_observed_complexity": "max-observed",
    "empirical_family_version_inference": "family-inference",
    "empirical_mutator_no_unpacking": "mutator",
}


def corpus_keys() -> set[tuple[str, str]]:
    work = json.loads(
        (REPO / "empirical_results/qemu_runtime/worklist.json").read_text())
    return {(str(w.get("family")).lower(), str(w.get("version"))) for w in work}


def main() -> int:
    rows: dict[tuple[str, str], dict] = {}
    corpus = corpus_keys()
    manifests = sorted(glob.glob(str(REPO / "manifest" / "empirical_types_*.yaml")))
    for path in manifests:
        data = yaml.safe_load(Path(path).read_text(encoding="utf-8")) or {}
        for cond in data.get("conditions", []):
            status = cond.get("label_status")
            label = cond.get("label")
            if not label or status in {"provisional_stack_cross_check",
                                       "pending_dynamic_evidence"}:
                continue
            # configuration_id is NOT unique -- gui-ba37f4c8f00e is shared by four
            # yoda_protector versions -- so keying on it silently merged distinct
            # conditions and under-reported the total.
            key = (str(cond.get("packer_family")).lower(),
                   str(cond.get("packer_version")))
            if key not in corpus:
                continue
            rows[key] = {
                "family": cond.get("packer_family"),
                "version": cond.get("packer_version"),
                "test_case": cond.get("test_case_id"),
                "label": label,
                "runs": cond.get("completed_runs"),
                "evidence": cond.get("paper_evidence_level"),
                "rule": RULE_BY_STATUS.get(status, status),
            }

    ordered = sorted(rows.values(), key=lambda r: (str(r["family"]).lower(),
                                                   str(r["version"]), str(r["test_case"])))
    lines = [
        "# Empirical Packer-Type Labels",
        "",
        "Exact Ugarte et al. Type I–VI labels assigned **empirically** from real",
        "dynamic traces of packed corpus samples (see",
        "[AUTOMATIC_LABELING.md](AUTOMATIC_LABELING.md)). Each row is an",
        "empirical label taken from the final manifests. The **Rule** column records",
        "which rule produced it -- `exact` is the strongest (same Type across ≥2 distinct",
        "packed payloads × ≥3 repetitions, certified backend); the others are weaker but",
        "still empirical, and stay distinguishable here. This file is generated by",
        "`ops/qemu/build_label_document.py` and grows as more conditions are run.",
        "",
        f"**Conditions empirically labeled: {len(ordered)}**",
        "",
        "| Packer family | Version | Test case | Empirical Type | Runs | Rule | Evidence |",
        "|---|---|---|---|---|---|---|",
    ]
    for r in ordered:
        lines.append(
            f"| {r['family']} | {r['version']} | {r['test_case']} | "
            f"**{r['label']}** | {r['runs']} | {r['rule']} | "
            f"{r['evidence'] or 'A_exact_layer_frame_trace'} |"
        )
    if not ordered:
        lines.append("| _(none yet — run a condition and finalize)_ | | | | | | |")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(ordered)} empirical labels")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
